### ISSUE TITLE
dots appearing off slider [with solution]

### ISSUE THREAD

**Issue by davidsomnus** [tantaman/jquery-gradient-picker#1]
Note that new jQuery UI draggable enforces the ControlPoints to be position:relative so your plugin is going to render the ControlPoints off the slider. I fixed it be overriding that after line 200 in jquery.gradientPicker.js (after the element has become draggable):

this.$el.css("position", 'absolute');

**Comment by tantaman** [comment]
Hey.  Wow it's really been 6 months :o

Anyhow, I'm re-working the gradient picker to no longer depend on jquery UI so this'll be a non-issue within a week.
